<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Analysis | SOPs for The Lab @ DC</title>
  <meta name="description" content="Standard Operating Procedures for Experiments and Data Analysis at The Lab @ DC." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Analysis | SOPs for The Lab @ DC" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Standard Operating Procedures for Experiments and Data Analysis at The Lab @ DC." />
  <meta name="github-repo" content="rtm-dc/LAB-SOP-experiments" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Analysis | SOPs for The Lab @ DC" />
  
  <meta name="twitter:description" content="Standard Operating Procedures for Experiments and Data Analysis at The Lab @ DC." />
  

<meta name="author" content="Ryan T. Moore" />


<meta name="date" content="2026-01-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="implementation.html"/>
<link rel="next" href="observational-studies.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.34.0/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/nouislider-7.0.10/jquery.nouislider.min.css" rel="stylesheet" />
<script src="libs/nouislider-7.0.10/jquery.nouislider.min.js"></script>
<link href="libs/selectize-0.12.0/selectize.bootstrap3.css" rel="stylesheet" />
<script src="libs/selectize-0.12.0/selectize.min.js"></script>
<link href="libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">SOPs for The Lab @ DC</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i>Colophon</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>1</b> Getting Started</a></li>
<li class="chapter" data-level="2" data-path="design.html"><a href="design.html"><i class="fa fa-check"></i><b>2</b> Design</a>
<ul>
<li class="chapter" data-level="2.1" data-path="design.html"><a href="design.html#units"><i class="fa fa-check"></i><b>2.1</b> Units</a></li>
<li class="chapter" data-level="2.2" data-path="design.html"><a href="design.html#level-of-randomization"><i class="fa fa-check"></i><b>2.2</b> Level of Randomization</a></li>
<li class="chapter" data-level="2.3" data-path="design.html"><a href="design.html#random-assignment-methods"><i class="fa fa-check"></i><b>2.3</b> Random Assignment Methods</a></li>
<li class="chapter" data-level="2.4" data-path="design.html"><a href="design.html#sec-blocking"><i class="fa fa-check"></i><b>2.4</b> Blocking on Background Characteristics</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="design.html"><a href="design.html#applications"><i class="fa fa-check"></i><b>2.4.1</b> Applications</a></li>
<li class="chapter" data-level="2.4.2" data-path="design.html"><a href="design.html#code-examples"><i class="fa fa-check"></i><b>2.4.2</b> Code Examples</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="design.html"><a href="design.html#sec-set-seed"><i class="fa fa-check"></i><b>2.5</b> Setting the Assignment Seed</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="design.html"><a href="design.html#seeding-procedures"><i class="fa fa-check"></i><b>2.5.1</b> Seeding Procedures</a></li>
<li class="chapter" data-level="2.5.2" data-path="design.html"><a href="design.html#updating-the-seed"><i class="fa fa-check"></i><b>2.5.2</b> Updating the Seed</a></li>
<li class="chapter" data-level="2.5.3" data-path="design.html"><a href="design.html#motivation"><i class="fa fa-check"></i><b>2.5.3</b> Motivation</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="design.html"><a href="design.html#power"><i class="fa fa-check"></i><b>2.6</b> Power</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="design.html"><a href="design.html#formula-based-power-analysis"><i class="fa fa-check"></i><b>2.6.1</b> Formula-based Power Analysis</a></li>
<li class="chapter" data-level="2.6.2" data-path="design.html"><a href="design.html#formula-based-mde-minimum-detectable-effect"><i class="fa fa-check"></i><b>2.6.2</b> Formula-based MDE (minimum detectable effect)</a></li>
<li class="chapter" data-level="2.6.3" data-path="design.html"><a href="design.html#simulation-based-power-analysis"><i class="fa fa-check"></i><b>2.6.3</b> Simulation-based Power Analysis</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="design.html"><a href="design.html#balance-checking"><i class="fa fa-check"></i><b>2.7</b> Balance Checking</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="implementation.html"><a href="implementation.html"><i class="fa fa-check"></i><b>3</b> Implementation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="implementation.html"><a href="implementation.html#along-the-way"><i class="fa fa-check"></i><b>3.1</b> Along the Way</a></li>
<li class="chapter" data-level="3.2" data-path="implementation.html"><a href="implementation.html#immediately-before-the-final-randomization"><i class="fa fa-check"></i><b>3.2</b> Immediately Before the Final Randomization</a></li>
<li class="chapter" data-level="3.3" data-path="implementation.html"><a href="implementation.html#the-final-randomization"><i class="fa fa-check"></i><b>3.3</b> The Final Randomization</a></li>
<li class="chapter" data-level="3.4" data-path="implementation.html"><a href="implementation.html#immediately-after-the-final-randomization"><i class="fa fa-check"></i><b>3.4</b> Immediately After the Final Randomization</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="analysis.html"><a href="analysis.html"><i class="fa fa-check"></i><b>4</b> Analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="analysis.html"><a href="analysis.html#notation"><i class="fa fa-check"></i><b>4.1</b> Notation</a></li>
<li class="chapter" data-level="4.2" data-path="analysis.html"><a href="analysis.html#estimands"><i class="fa fa-check"></i><b>4.2</b> Estimands</a></li>
<li class="chapter" data-level="4.3" data-path="analysis.html"><a href="analysis.html#sec-unadj-itt"><i class="fa fa-check"></i><b>4.3</b> The Unadjusted ITT</a></li>
<li class="chapter" data-level="4.4" data-path="analysis.html"><a href="analysis.html#sec-lin"><i class="fa fa-check"></i><b>4.4</b> Adjusting for Covariates</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="analysis.html"><a href="analysis.html#why-we-adjust-for-covariates"><i class="fa fa-check"></i><b>4.4.1</b> Why we adjust for covariates</a></li>
<li class="chapter" data-level="4.4.2" data-path="analysis.html"><a href="analysis.html#how-we-adjust-for-covariates"><i class="fa fa-check"></i><b>4.4.2</b> How we adjust for covariates</a></li>
<li class="chapter" data-level="4.4.3" data-path="analysis.html"><a href="analysis.html#sec-smallcells"><i class="fa fa-check"></i><b>4.4.3</b> Lin Adjustment with Small Cells</a></li>
<li class="chapter" data-level="4.4.4" data-path="analysis.html"><a href="analysis.html#sec-weights-dof"><i class="fa fa-check"></i><b>4.4.4</b> Note: Weighted Adjustment and Degrees of Freedom</a></li>
<li class="chapter" data-level="4.4.5" data-path="analysis.html"><a href="analysis.html#sec-adjust-blocks"><i class="fa fa-check"></i><b>4.4.5</b> Adjusting for Blocks</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="analysis.html"><a href="analysis.html#sec-binary-outcomes"><i class="fa fa-check"></i><b>4.5</b> Binary or Count Outcomes</a></li>
<li class="chapter" data-level="4.6" data-path="analysis.html"><a href="analysis.html#clusters-weights-fixed-effects"><i class="fa fa-check"></i><b>4.6</b> Clusters, Weights, Fixed Effects</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="analysis.html"><a href="analysis.html#weights"><i class="fa fa-check"></i><b>4.6.1</b> Weights</a></li>
<li class="chapter" data-level="4.6.2" data-path="analysis.html"><a href="analysis.html#fixed-effects"><i class="fa fa-check"></i><b>4.6.2</b> Fixed Effects</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="analysis.html"><a href="analysis.html#sec-rand-inf"><i class="fa fa-check"></i><b>4.7</b> Randomization Inference</a></li>
<li class="chapter" data-level="4.8" data-path="analysis.html"><a href="analysis.html#addressing-non-compliance"><i class="fa fa-check"></i><b>4.8</b> Addressing Non-compliance</a></li>
<li class="chapter" data-level="4.9" data-path="analysis.html"><a href="analysis.html#missing-data"><i class="fa fa-check"></i><b>4.9</b> Missing Data</a></li>
<li class="chapter" data-level="4.10" data-path="analysis.html"><a href="analysis.html#multiple-comparisons"><i class="fa fa-check"></i><b>4.10</b> Multiple Comparisons</a>
<ul>
<li class="chapter" data-level="4.10.1" data-path="analysis.html"><a href="analysis.html#holm-bonferroni-adjustment"><i class="fa fa-check"></i><b>4.10.1</b> Holm-Bonferroni Adjustment</a></li>
<li class="chapter" data-level="4.10.2" data-path="analysis.html"><a href="analysis.html#westfall-young-adjustment"><i class="fa fa-check"></i><b>4.10.2</b> Westfall-Young Adjustment</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="analysis.html"><a href="analysis.html#posterior-probabilities"><i class="fa fa-check"></i><b>4.11</b> Posterior Probabilities</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="observational-studies.html"><a href="observational-studies.html"><i class="fa fa-check"></i><b>5</b> Observational Studies</a>
<ul>
<li class="chapter" data-level="5.1" data-path="observational-studies.html"><a href="observational-studies.html#matching"><i class="fa fa-check"></i><b>5.1</b> Matching</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="observational-studies.html"><a href="observational-studies.html#methods"><i class="fa fa-check"></i><b>5.1.1</b> Methods</a></li>
<li class="chapter" data-level="5.1.2" data-path="observational-studies.html"><a href="observational-studies.html#selecting-the-method-for-analysis"><i class="fa fa-check"></i><b>5.1.2</b> Selecting the Method for Analysis</a></li>
<li class="chapter" data-level="5.1.3" data-path="observational-studies.html"><a href="observational-studies.html#calipers"><i class="fa fa-check"></i><b>5.1.3</b> Calipers</a></li>
<li class="chapter" data-level="5.1.4" data-path="observational-studies.html"><a href="observational-studies.html#alternatives"><i class="fa fa-check"></i><b>5.1.4</b> Alternatives</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="publication.html"><a href="publication.html"><i class="fa fa-check"></i><b>6</b> Publication</a>
<ul>
<li class="chapter" data-level="6.1" data-path="publication.html"><a href="publication.html#authorship"><i class="fa fa-check"></i><b>6.1</b> Authorship</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="publication.html"><a href="publication.html#sec-labcredit"><i class="fa fa-check"></i><b>6.1.1</b> CRediT Roles at The Lab @ DC</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="publication.html"><a href="publication.html#publishing-data"><i class="fa fa-check"></i><b>6.2</b> Publishing Data</a></li>
<li class="chapter" data-level="6.3" data-path="publication.html"><a href="publication.html#presenting-results"><i class="fa fa-check"></i><b>6.3</b> Presenting Results</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="publication.html"><a href="publication.html#estimates-and-uncertainties"><i class="fa fa-check"></i><b>6.3.1</b> Estimates and uncertainties</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="r-basics.html"><a href="r-basics.html"><i class="fa fa-check"></i><b>A</b> R Basics</a>
<ul>
<li class="chapter" data-level="A.1" data-path="r-basics.html"><a href="r-basics.html#get-r-and-rstudio"><i class="fa fa-check"></i><b>A.1</b> Get R and RStudio</a></li>
<li class="chapter" data-level="A.2" data-path="r-basics.html"><a href="r-basics.html#read-in-data-files"><i class="fa fa-check"></i><b>A.2</b> Read in data files</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="r-basics.html"><a href="r-basics.html#csv"><i class="fa fa-check"></i><b>A.2.1</b> <code>.csv</code></a></li>
<li class="chapter" data-level="A.2.2" data-path="r-basics.html"><a href="r-basics.html#xlsx"><i class="fa fa-check"></i><b>A.2.2</b> <code>.xlsx</code></a></li>
<li class="chapter" data-level="A.2.3" data-path="r-basics.html"><a href="r-basics.html#box"><i class="fa fa-check"></i><b>A.2.3</b> Box</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="r-basics.html"><a href="r-basics.html#pipes"><i class="fa fa-check"></i><b>A.3</b> Pipes</a></li>
<li class="chapter" data-level="A.4" data-path="r-basics.html"><a href="r-basics.html#rename-variables"><i class="fa fa-check"></i><b>A.4</b> Rename variables</a></li>
<li class="chapter" data-level="A.5" data-path="r-basics.html"><a href="r-basics.html#create-a-new-variable"><i class="fa fa-check"></i><b>A.5</b> Create a New Variable</a>
<ul>
<li class="chapter" data-level="A.5.1" data-path="r-basics.html"><a href="r-basics.html#create-a-wave-id"><i class="fa fa-check"></i><b>A.5.1</b> Create a “wave ID”</a></li>
<li class="chapter" data-level="A.5.2" data-path="r-basics.html"><a href="r-basics.html#create-a-primary-key"><i class="fa fa-check"></i><b>A.5.2</b> Create a primary key</a></li>
<li class="chapter" data-level="A.5.3" data-path="r-basics.html"><a href="r-basics.html#transform-an-existing-variable"><i class="fa fa-check"></i><b>A.5.3</b> Transform an existing variable</a></li>
<li class="chapter" data-level="A.5.4" data-path="r-basics.html"><a href="r-basics.html#create-a-sum-from-a-subset-of-variables"><i class="fa fa-check"></i><b>A.5.4</b> Create a sum from a subset of variables</a></li>
</ul></li>
<li class="chapter" data-level="A.6" data-path="r-basics.html"><a href="r-basics.html#recode-a-variables-values"><i class="fa fa-check"></i><b>A.6</b> Recode a variable’s values</a></li>
<li class="chapter" data-level="A.7" data-path="r-basics.html"><a href="r-basics.html#treat-dates-as-dates"><i class="fa fa-check"></i><b>A.7</b> Treat dates as dates</a>
<ul>
<li class="chapter" data-level="A.7.1" data-path="r-basics.html"><a href="r-basics.html#make-an-age-variable"><i class="fa fa-check"></i><b>A.7.1</b> Make an age variable</a></li>
<li class="chapter" data-level="A.7.2" data-path="r-basics.html"><a href="r-basics.html#make-a-month-count-variable"><i class="fa fa-check"></i><b>A.7.2</b> Make a month-count variable</a></li>
</ul></li>
<li class="chapter" data-level="A.8" data-path="r-basics.html"><a href="r-basics.html#sec-create-treatment"><i class="fa fa-check"></i><b>A.8</b> Create a completely randomised indicator</a></li>
<li class="chapter" data-level="A.9" data-path="r-basics.html"><a href="r-basics.html#plot-a-variable"><i class="fa fa-check"></i><b>A.9</b> Plot a variable</a></li>
<li class="chapter" data-level="A.10" data-path="r-basics.html"><a href="r-basics.html#calculate-a-data-summary"><i class="fa fa-check"></i><b>A.10</b> Calculate a data summary</a>
<ul>
<li class="chapter" data-level="A.10.1" data-path="r-basics.html"><a href="r-basics.html#proportions-for-a-categorical-variable"><i class="fa fa-check"></i><b>A.10.1</b> Proportions for a categorical variable</a></li>
<li class="chapter" data-level="A.10.2" data-path="r-basics.html"><a href="r-basics.html#proportions-for-binary-variables"><i class="fa fa-check"></i><b>A.10.2</b> Proportions for binary variables</a></li>
</ul></li>
<li class="chapter" data-level="A.11" data-path="r-basics.html"><a href="r-basics.html#merge-join-dataframes"><i class="fa fa-check"></i><b>A.11</b> Merge (join) dataframes</a></li>
<li class="chapter" data-level="A.12" data-path="r-basics.html"><a href="r-basics.html#anonymize-sensitive-data"><i class="fa fa-check"></i><b>A.12</b> Anonymize sensitive data</a>
<ul>
<li class="chapter" data-level="A.12.1" data-path="r-basics.html"><a href="r-basics.html#salting"><i class="fa fa-check"></i><b>A.12.1</b> Salting</a></li>
</ul></li>
<li class="chapter" data-level="A.13" data-path="r-basics.html"><a href="r-basics.html#deal-with-factors-orderedunordered-in-models"><i class="fa fa-check"></i><b>A.13</b> Deal with factors (ordered/unordered) in models</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html"><i class="fa fa-check"></i><b>B</b> Python Basics (using R/RStudio)</a>
<ul>
<li class="chapter" data-level="B.1" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#installing-tools-r-packages-and-python"><i class="fa fa-check"></i><b>B.1</b> Installing tools, R packages, and Python</a>
<ul>
<li class="chapter" data-level="B.1.1" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#get-rtools"><i class="fa fa-check"></i><b>B.1.1</b> Get Rtools</a></li>
<li class="chapter" data-level="B.1.2" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#get-tinytex"><i class="fa fa-check"></i><b>B.1.2</b> Get <code>tinytex</code></a></li>
<li class="chapter" data-level="B.1.3" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#get-python"><i class="fa fa-check"></i><b>B.1.3</b> Get Python</a></li>
<li class="chapter" data-level="B.1.4" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#configure-python"><i class="fa fa-check"></i><b>B.1.4</b> Configure Python</a></li>
<li class="chapter" data-level="B.1.5" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#get-reticulate"><i class="fa fa-check"></i><b>B.1.5</b> Get <code>reticulate</code></a></li>
</ul></li>
<li class="chapter" data-level="B.2" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#using-python"><i class="fa fa-check"></i><b>B.2</b> Using Python</a>
<ul>
<li class="chapter" data-level="B.2.1" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#from-a-python-prompt"><i class="fa fa-check"></i><b>B.2.1</b> From a Python prompt</a></li>
<li class="chapter" data-level="B.2.2" data-path="python-basics-using-rrstudio.html"><a href="python-basics-using-rrstudio.html#from-inside-a-quarto-document"><i class="fa fa-check"></i><b>B.2.2</b> From inside a Quarto document</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html"><i class="fa fa-check"></i><b>C</b> Managing Code and Scientific Communication</a>
<ul>
<li class="chapter" data-level="C.1" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#best-practices"><i class="fa fa-check"></i><b>C.1</b> Best Practices</a></li>
<li class="chapter" data-level="C.2" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#style"><i class="fa fa-check"></i><b>C.2</b> Style</a>
<ul>
<li class="chapter" data-level="C.2.1" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#r"><i class="fa fa-check"></i><b>C.2.1</b> R</a></li>
<li class="chapter" data-level="C.2.2" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#equations"><i class="fa fa-check"></i><b>C.2.2</b> Equations</a></li>
<li class="chapter" data-level="C.2.3" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#statistical-quantities"><i class="fa fa-check"></i><b>C.2.3</b> Statistical Quantities</a></li>
</ul></li>
<li class="chapter" data-level="C.3" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#sec-projects"><i class="fa fa-check"></i><b>C.3</b> Projects</a></li>
<li class="chapter" data-level="C.4" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#sec-working-dir"><i class="fa fa-check"></i><b>C.4</b> Working Directory and Relative Paths</a>
<ul>
<li class="chapter" data-level="C.4.1" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#see-the-working-directory"><i class="fa fa-check"></i><b>C.4.1</b> See the working directory</a></li>
<li class="chapter" data-level="C.4.2" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#see-the-project-directory"><i class="fa fa-check"></i><b>C.4.2</b> See the project directory</a></li>
<li class="chapter" data-level="C.4.3" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#create-a-path-with-here"><i class="fa fa-check"></i><b>C.4.3</b> Create a path with <code>here()</code></a></li>
</ul></li>
<li class="chapter" data-level="C.5" data-path="managing-code-and-scientific-communication.html"><a href="managing-code-and-scientific-communication.html#what-packages-are-installed"><i class="fa fa-check"></i><b>C.5</b> What Packages are Installed?</a></li>
</ul></li>
<li class="chapter" data-level="D" data-path="getting-started-with-git-and-github.html"><a href="getting-started-with-git-and-github.html"><i class="fa fa-check"></i><b>D</b> Getting Started with <code>git</code> and GitHub</a></li>
<li class="chapter" data-level="E" data-path="introductory-reading-at-the-lab-dc.html"><a href="introductory-reading-at-the-lab-dc.html"><i class="fa fa-check"></i><b>E</b> Introductory Reading at The Lab @ DC</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">SOPs for The Lab @ DC</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analysis" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Analysis<a href="analysis.html#analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In experiments, our standard operating procedure is to estimate the treatment
effect via</p>
<ul>
<li>the <a href="analysis.html#sec-unadj-itt">unadjusted</a> ITT</li>
<li>the <a href="analysis.html#sec-lin">adjusted</a> ITT, where we have potentially informative covariates</li>
</ul>
<p>We incorporate features of our design into our analysis. This includes blocking,
<a href="analysis.html#clusters-weights-fixed-effects">clustering</a>, and <a href="analysis.html#weights">weighting</a> when
treatment assignment probabilities vary.</p>
<p>By default, we perform parametric statistical inference using HC2 standard
errors if our assignment is not clustered. If our assignment is clustered, we
use CR2 standard errors with <a href="analysis.html#clusters-weights-fixed-effects">clustering</a> at
the level of assignment.</p>
<p>Often, however, we specify that we will use design-based <a href="analysis.html#sec-rand-inf">randomization
inference</a> instead of parametric inference. This
design-based inference attempts to replicate all the features of our assignment
and analysis. Some times that we rely on randomization inference include when we
have a multistage or wave-based design that creates complex assignment
probabilities, a skewed outcome<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> or
other distributional concern, or a novel adjustment strategy.</p>
<p>We report treatment effect estimates and associated confidence intervals. We
often report the <a href="analysis.html#posterior-probabilities">posterior probability</a> that one
condition is better than another.</p>
<div id="notation" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Notation<a href="analysis.html#notation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Notation:</p>
<ul>
<li><span class="math inline">\(n\)</span> units, indexed <span class="math inline">\(i \in \{1, \ldots, n\}\)</span></li>
<li><span class="math inline">\(Z_i \in \{0, 1\}\)</span> indicates <em>assignment</em> to the control or treatment condition</li>
<li><span class="math inline">\(D_i \in \{0, 1\}\)</span> indicates <em>receipt</em> of the control or treatment condition</li>
<li><span class="math inline">\(Y_i(1)\)</span> the potential outcome for unit <span class="math inline">\(i\)</span> if assigned to treatment (more explicitly, <span class="math inline">\(Y_i(Z_i = 1)\)</span>)</li>
<li><span class="math inline">\(Y_i(0)\)</span> the potential outcome for unit <span class="math inline">\(i\)</span> if assigned to control</li>
<li><span class="math inline">\(Y_i\)</span> the <em>observed</em> potential outcome for unit <span class="math inline">\(i\)</span></li>
</ul>
</div>
<div id="estimands" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Estimands<a href="analysis.html#estimands" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below are some estimands (targets) that we may be interested in.</p>
<ul>
<li>Average treatment effect: <span class="math inline">\(ATE = \frac{1}{n} \sum\limits_{i=1}^{n} (Y_i(1) - Y_i(0))\)</span></li>
<li>LATE CACE</li>
<li>Effect for those most helped <span class="citation">(<a href="#ref-rugfol21">Ruggeri and Folke 2021</a>)</span></li>
</ul>
</div>
<div id="sec-unadj-itt" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> The Unadjusted ITT<a href="analysis.html#sec-unadj-itt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>By default, in experiments, we estimate the intent-to-treat effect (ITT),
unadjusted for covariates, using HC2 standard errors for inference. We do so by
estimating the coefficients of the model</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 Z_i + \epsilon_i\]</span>
using least squares. First, some preliminaries:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="analysis.html#cb37-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb37-2"><a href="analysis.html#cb37-2" tabindex="-1"></a><span class="fu">library</span>(estimatr)</span>
<span id="cb37-3"><a href="analysis.html#cb37-3" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb37-4"><a href="analysis.html#cb37-4" tabindex="-1"></a></span>
<span id="cb37-5"><a href="analysis.html#cb37-5" tabindex="-1"></a><span class="co"># Load data:</span></span>
<span id="cb37-6"><a href="analysis.html#cb37-6" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;02-01-df.RData&quot;</span>))</span></code></pre></div>
<p>Our estimation procedure:</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="analysis.html#cb38-1" tabindex="-1"></a>lm_out <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(y <span class="sc">~</span> z, <span class="at">data =</span> df)</span>
<span id="cb38-2"><a href="analysis.html#cb38-2" tabindex="-1"></a></span>
<span id="cb38-3"><a href="analysis.html#cb38-3" tabindex="-1"></a>lm_out</span></code></pre></div>
<pre><code>##             Estimate Std. Error  t value     Pr(&gt;|t|)  CI Lower CI Upper DF
## (Intercept) 2.631066  0.2866799 9.177716 7.370994e-15 2.0621596 3.199973 98
## z           1.548357  0.5367332 2.884779 4.816584e-03 0.4832272 2.613486 98</code></pre>
<p>We can view the ITT treatment effect from the model object with
<code>summary(lm_out)</code> or extract it with <code>lm_out$coefficients["z"]</code>.</p>
</div>
<div id="sec-lin" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Adjusting for Covariates<a href="analysis.html#sec-lin" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="why-we-adjust-for-covariates" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> Why we adjust for covariates<a href="analysis.html#why-we-adjust-for-covariates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We adjust for covariates for two reasons. First, we adjust to address covariate imbalances that remain in our sample, in order to minimize our estimation error. As <span class="citation">Tukey (<a href="#ref-tukey91">1991, 123</a>)</span> describes,</p>
<blockquote>
<p>the degree of protection against either the consequences of inadequate randomization or the (random) occurrence of an unusual randomization is considerably increased by adjustment.<br />
<em>Greater security, rather than increased precision, or increased sensitivity will often be the basic reason for covariance adjustment in a randomized trial.</em></p>
</blockquote>
<p>Despite the fact that the difference in means and regression equivalents are unbiased for the ATE under random allocation, we can only derive estimates from the sample at hand.</p>
<p>Second, adjustment can increase our ATE estimate precision.</p>
</div>
<div id="how-we-adjust-for-covariates" class="section level3 hasAnchor" number="4.4.2">
<h3><span class="header-section-number">4.4.2</span> How we adjust for covariates<a href="analysis.html#how-we-adjust-for-covariates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To estimate average treatment effects in experiments, we follow the guidance of <span class="citation">Lin (<a href="#ref-lin2013">2013</a>)</span>, using HC2 standard
errors for inference, and, where we adjust for covariates, centering and
interacting predictors with treatment status. Where <span class="math inline">\(Z\)</span> is treatment status and
<span class="math inline">\(X\)</span> is a covariate, <span class="math inline">\(\beta_1\)</span> below is the ATE:</p>
<p><span class="math display">\[y_i = \beta_0 + \beta_1 Z_i + \beta_2 (X_i - \bar{X}) + \beta_3 Z_i (X_i - \bar{X}) + \epsilon_i\]</span>
To implement this, we can use <code>lm_lin()</code> from the <code>estimatr</code> package<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a>:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="analysis.html#cb40-1" tabindex="-1"></a>lin_out <span class="ot">&lt;-</span> <span class="fu">lm_lin</span>(y <span class="sc">~</span> z, <span class="at">covariates =</span> <span class="sc">~</span> x, <span class="at">data =</span> df)</span>
<span id="cb40-2"><a href="analysis.html#cb40-2" tabindex="-1"></a>lin_out</span></code></pre></div>
<pre><code>##              Estimate Std. Error  t value     Pr(&gt;|t|)    CI Lower  CI Upper DF
## (Intercept) 2.8816525 0.15663330 18.39744 3.088795e-33  2.57073780 3.1925671 96
## z           0.9487427 0.23402169  4.05408 1.023250e-04  0.48421335 1.4132721 96
## x_c         0.8773304 0.06813581 12.87620 1.239045e-22  0.74208190 1.0125789 96
## z:x_c       0.1224778 0.08153824  1.50209 1.363561e-01 -0.03937434 0.2843299 96</code></pre>
<p>We can view the adjusted ITT treatment effect from the model object with
<code>summary(lin_out)</code> or extract it with <code>lin_out$coefficients["z"]</code>.</p>
<p>The estimate of the average treatment effect is <span class="math inline">\(0.949\)</span>, with a 95% confidence
interval covering <span class="math inline">\((0.484, 1.413)\)</span>.</p>
<p>When we want to adjust for a factor variable that has many levels, the interactions in the Lin estimator may not all be identified. In this case, when we want the Lin estimate of the ATE, we coarsen the factor into fewer categories.</p>
<p>Sometimes we are interested in quantities other than average treatment effects. For example, in an <a href="https://thelabprojects.dc.gov/high-risk-drivers">experiment</a> involving safety messaging, we might have exploratory interest in whether different models of cars’ registrants appear to behave differently. In such an exploration, we estimate a linear model with a coefficient for each car model without centering and interacting the predictors.</p>
</div>
<div id="sec-smallcells" class="section level3 hasAnchor" number="4.4.3">
<h3><span class="header-section-number">4.4.3</span> Lin Adjustment with Small Cells<a href="analysis.html#sec-smallcells" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the example above, there are <em>many</em> models of cars that appear in the data.
In cases like this, models with category-by-treatment interactions may demand more than the data can provide – a
treatment and control unit for every car model.</p>
</div>
<div id="sec-weights-dof" class="section level3 hasAnchor" number="4.4.4">
<h3><span class="header-section-number">4.4.4</span> Note: Weighted Adjustment and Degrees of Freedom<a href="analysis.html#sec-weights-dof" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When estimating a weighted regression, base R’s <code>lm()</code> and <code>{estimatr}</code>’s <code>lm_lin()</code> and <code>lm_robust()</code> return different values for the residual degrees of freedom.</p>
<ul>
<li><code>lm()</code> returns the quantity (sample size) - (sample size that has weight = zero) - (number of parameters)</li>
<li><code>lm_lin()</code> and <code>lm_robust()</code> return the quantity (sample size) - (number of parameters), ignoring the fact that some observations may have weight <span class="math inline">\(=0\)</span>.</li>
</ul>
<p>A code example follows.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="analysis.html#cb42-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb42-2"><a href="analysis.html#cb42-2" tabindex="-1"></a></span>
<span id="cb42-3"><a href="analysis.html#cb42-3" tabindex="-1"></a><span class="co"># Simulate data:</span></span>
<span id="cb42-4"><a href="analysis.html#cb42-4" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">452821792</span>)</span>
<span id="cb42-5"><a href="analysis.html#cb42-5" tabindex="-1"></a></span>
<span id="cb42-6"><a href="analysis.html#cb42-6" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb42-7"><a href="analysis.html#cb42-7" tabindex="-1"></a></span>
<span id="cb42-8"><a href="analysis.html#cb42-8" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb42-9"><a href="analysis.html#cb42-9" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">rnorm</span>(n),</span>
<span id="cb42-10"><a href="analysis.html#cb42-10" tabindex="-1"></a>  <span class="at">t =</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-11"><a href="analysis.html#cb42-11" tabindex="-1"></a>  <span class="at">y =</span> t <span class="sc">+</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(n),</span>
<span id="cb42-12"><a href="analysis.html#cb42-12" tabindex="-1"></a>  <span class="at">w =</span> <span class="fu">runif</span>(n, <span class="dv">0</span>, <span class="dv">3</span>),</span>
<span id="cb42-13"><a href="analysis.html#cb42-13" tabindex="-1"></a>  <span class="at">w_zero =</span> <span class="fu">if_else</span>(w <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="dv">0</span>, w)</span>
<span id="cb42-14"><a href="analysis.html#cb42-14" tabindex="-1"></a>)</span></code></pre></div>
<p>Note that 35 observations have weight <span class="math inline">\(=0\)</span>:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="analysis.html#cb43-1" tabindex="-1"></a>df <span class="sc">|&gt;</span> <span class="fu">count</span>(w_zero <span class="sc">==</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   `w_zero == 0`     n
##   &lt;lgl&gt;         &lt;int&gt;
## 1 FALSE           165
## 2 TRUE             35</code></pre>
<p>Three weighted regression estimations’ degrees of freedom:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="analysis.html#cb45-1" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> t <span class="sc">+</span> x, <span class="at">weights =</span> w, <span class="at">data =</span> df)<span class="sc">$</span>df</span></code></pre></div>
<pre><code>## [1] 197</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="analysis.html#cb47-1" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> t <span class="sc">+</span> x, <span class="at">weights =</span> w_zero, <span class="at">data =</span> df)<span class="sc">$</span>df</span></code></pre></div>
<pre><code>## [1] 162</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="analysis.html#cb49-1" tabindex="-1"></a><span class="fu">lm_robust</span>(y <span class="sc">~</span> t <span class="sc">+</span> x, <span class="at">data =</span> df, <span class="at">weights =</span> w_zero) <span class="sc">|&gt;</span> </span>
<span id="cb49-2"><a href="analysis.html#cb49-2" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, df)</span></code></pre></div>
<pre><code>##          term  estimate  df
## 1 (Intercept) 0.0621577 197
## 2           t 0.8892474 197
## 3           x 1.0421735 197</code></pre>
</div>
<div id="sec-adjust-blocks" class="section level3 hasAnchor" number="4.4.5">
<h3><span class="header-section-number">4.4.5</span> Adjusting for Blocks<a href="analysis.html#sec-adjust-blocks" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Where treatment probabilities or sample sizes vary across blocks we account for our blocking by either treating the block indicators <span class="math inline">\(B_j\)</span> as Lin covariates and estimating</p>
<p><span class="math display">\[\begin{eqnarray*}
y_i &amp; = &amp;  \beta_0 + \beta_1 Z_i + \beta_2 (X_i - \bar{X}) + \beta_3 Z_i (X_i - \bar{X}) + \ldots \\
&amp;&amp; \gamma_1 (B_1 - \bar{B}_1) + \gamma_2 (B_2 - \bar{B}_2) + \ldots \\
&amp;&amp; \delta_1 Z_i (B_1 - \bar{B}_1) + \delta_2 Z_i (B_2 - \bar{B}_2) + \ldots + \epsilon_i
\end{eqnarray*}\]</span></p>
<p>or by estimating the blocked difference-in-means (i.e., taking the average of the block-level ATEs, weighted by their sample sizes). We can do so via</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="analysis.html#cb51-1" tabindex="-1"></a><span class="fu">lm_lin</span>(y <span class="sc">~</span> z, <span class="at">covariates =</span> <span class="sc">~</span> x <span class="sc">+</span> block1_id <span class="sc">+</span> block2_id <span class="sc">+</span> ..., <span class="at">data =</span> df)</span>
<span id="cb51-2"><a href="analysis.html#cb51-2" tabindex="-1"></a><span class="fu">lm_lin</span>(y <span class="sc">~</span> z, <span class="at">covariates =</span> <span class="sc">~</span> x <span class="sc">+</span> block_id_factor, <span class="at">data =</span> df)</span></code></pre></div>
<p>We do this because the “least squares dummy variable” approach produces biased
estimates of the ATE and its standard error. This approach weights block-level
effects by <span class="math inline">\(p_j(1-p_j)n_j\)</span>, where <span class="math inline">\(p_j\)</span> is the probability of treatment in the
block, and <span class="math inline">\(n_j\)</span> is the sample size in the block. See the helpful blog post
<a href="https://declaredesign.org/blog/posts/biased-fixed-effects.html">here</a>.</p>
</div>
</div>
<div id="sec-binary-outcomes" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Binary or Count Outcomes<a href="analysis.html#sec-binary-outcomes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We estimate the linear models above, even when we have binary or count outcomes. The Lin
estimator returns a good estimate of the difference in means of non-normal outcomes; <span class="citation">Lin (<a href="#ref-lin2013">2013</a>)</span>
provides an example with a highly skewed outcome, e.g.</p>
</div>
<div id="clusters-weights-fixed-effects" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Clusters, Weights, Fixed Effects<a href="analysis.html#clusters-weights-fixed-effects" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To specify other design or estimation components for <code>lm_robust()</code> or
<code>lm_lin()</code>, start at the help file at
<a href="https://declaredesign.org/r/estimatr/reference/lm_robust.html" class="uri">https://declaredesign.org/r/estimatr/reference/lm_robust.html</a>. For example, for
a clustered assignment analysis,</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="analysis.html#cb52-1" tabindex="-1"></a><span class="fu">lm_robust</span>(y <span class="sc">~</span> z, <span class="at">data =</span> df, <span class="at">clusters =</span> cluster_id)</span></code></pre></div>
<p>Though our standard procedure is to cluster at the level of assignment, we note
that “<a href="https://declaredesign.org/blog/posts/sometimes-you-need-to-cluster-standard-errors-above-level-of-treatment.html">[s]ometimes you need to cluster standard errors above the level of
treatment</a>.”</p>
<div id="weights" class="section level3 hasAnchor" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Weights<a href="analysis.html#weights" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>When our units have different probabilities of assignment, we weight each unit
by the reciprocal of the probability of being assigned to the condition that the
unit is finally assigned to. We use <em>inverse probability weights</em> (IPW).<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<p>For example, suppose we have a monthly lottery from January to March, and those
not selected for the program in the first month are still eligible to be
selected in the second month. See <span class="citation">Avila et al. (<a href="#ref-avimammoo23">2023</a>)</span> for an example. Person <span class="math inline">\(A\)</span> is
eligible for all three waves of a lottery because they apply in January and
could be repeatedly assigned to the control group; person <span class="math inline">\(B\)</span> applies in March
and is only eligible in the last lottery.</p>
<p>If the probability of treatment in each wave is <span class="math inline">\(p\)</span>, then the probabilities of
treatment and control for <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are</p>
<table>
<thead>
<tr class="header">
<th align="center">Unit</th>
<th align="center">Entry</th>
<th align="center"><span class="math inline">\(Pr(Z = 1)\)</span></th>
<th align="center"><span class="math inline">\(Pr(Z = 0)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(A\)</span></td>
<td align="center">January</td>
<td align="center"><span class="math inline">\(p + (1-p)p + (1-p)^2p\)</span></td>
<td align="center"><span class="math inline">\(1-[p + (1-p)p + (1-p)^2p]\)</span></td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(B\)</span></td>
<td align="center">March</td>
<td align="center"><span class="math inline">\(p\)</span></td>
<td align="center"><span class="math inline">\(1-p\)</span></td>
</tr>
</tbody>
</table>
<p>and the weights are</p>
<table>
<colgroup>
<col width="11%" />
<col width="14%" />
<col width="37%" />
<col width="37%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Unit</th>
<th align="center">Entry</th>
<th align="center">IPW if <span class="math inline">\((Z = 1)\)</span></th>
<th align="center">IPW if <span class="math inline">\(Z = 0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(A\)</span></td>
<td align="center">January</td>
<td align="center"><span class="math inline">\(\frac{1}{p + (1-p)p + (1-p)^2p}\)</span></td>
<td align="center"><span class="math inline">\(\frac{1}{1-[p + (1-p)p + (1-p)^2p]}\)</span></td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(B\)</span></td>
<td align="center">March</td>
<td align="center"><span class="math inline">\(\frac{1}{p}\)</span></td>
<td align="center"><span class="math inline">\(\frac{1}{1-p}\)</span></td>
</tr>
</tbody>
</table>
<p>If the assignment probability varies by wave, i.e., <span class="math inline">\(p\)</span> is not constant, then
this fact needs to be taken into account.</p>
</div>
<div id="fixed-effects" class="section level3 hasAnchor" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Fixed Effects<a href="analysis.html#fixed-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We note that treatment effect estimates from two-way fixed effect (TWFE)
event-study regressions “<a href="https://bcallaway11.github.io/did/articles/TWFE.html">can be severely
biased</a>”, even with
homogeneous treatment effects.</p>
</div>
</div>
<div id="sec-rand-inf" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Randomization Inference<a href="analysis.html#sec-rand-inf" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Often, we prefer to rely on our <em>design</em>, rather than asymptotic or
distributional assumptions, for statistical inference. In particular, when we
have complex designs or analysis strategies, we use randomization inference.</p>
<p>For example, with modest sample sizes and a complex experimental design, in
<span class="citation">Avila et al. (<a href="#ref-avimammoo23">2023</a>)</span> we use randomization inference. Below is an annotated example of
doing so, using a <code>for</code> loop. We set the seed using the method in Section
<a href="design.html#sec-set-seed">2.5</a>; we simulate treatment assignments using the method in
Section <a href="r-basics.html#sec-create-treatment">A.8</a>. More simulations reduces simulation error.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="analysis.html#cb53-1" tabindex="-1"></a><span class="co"># Set seed:</span></span>
<span id="cb53-2"><a href="analysis.html#cb53-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">534722898</span>)</span>
<span id="cb53-3"><a href="analysis.html#cb53-3" tabindex="-1"></a></span>
<span id="cb53-4"><a href="analysis.html#cb53-4" tabindex="-1"></a><span class="co"># Set simulation size:</span></span>
<span id="cb53-5"><a href="analysis.html#cb53-5" tabindex="-1"></a>n_sims <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb53-6"><a href="analysis.html#cb53-6" tabindex="-1"></a></span>
<span id="cb53-7"><a href="analysis.html#cb53-7" tabindex="-1"></a><span class="co"># Create empty storage vector:</span></span>
<span id="cb53-8"><a href="analysis.html#cb53-8" tabindex="-1"></a>store_te <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="st">&quot;double&quot;</span>, <span class="at">length =</span> n_sims)</span>
<span id="cb53-9"><a href="analysis.html#cb53-9" tabindex="-1"></a></span>
<span id="cb53-10"><a href="analysis.html#cb53-10" tabindex="-1"></a><span class="co"># Rerandomise and perform estimation n_sims times:</span></span>
<span id="cb53-11"><a href="analysis.html#cb53-11" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_sims){</span>
<span id="cb53-12"><a href="analysis.html#cb53-12" tabindex="-1"></a>  </span>
<span id="cb53-13"><a href="analysis.html#cb53-13" tabindex="-1"></a>  <span class="co"># Reassign 0/1 treatment:</span></span>
<span id="cb53-14"><a href="analysis.html#cb53-14" tabindex="-1"></a>  df_tmp <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">z_tmp =</span> <span class="fu">sample</span>(<span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="fu">n</span>(), <span class="at">replace =</span> <span class="cn">TRUE</span>))</span>
<span id="cb53-15"><a href="analysis.html#cb53-15" tabindex="-1"></a>  </span>
<span id="cb53-16"><a href="analysis.html#cb53-16" tabindex="-1"></a>  <span class="co"># Estimate treatment effect:</span></span>
<span id="cb53-17"><a href="analysis.html#cb53-17" tabindex="-1"></a>  lm_tmp <span class="ot">&lt;-</span> <span class="fu">lm_robust</span>(y <span class="sc">~</span> z_tmp, <span class="at">data =</span> df_tmp)</span>
<span id="cb53-18"><a href="analysis.html#cb53-18" tabindex="-1"></a>  </span>
<span id="cb53-19"><a href="analysis.html#cb53-19" tabindex="-1"></a>  <span class="co"># Store estimate:</span></span>
<span id="cb53-20"><a href="analysis.html#cb53-20" tabindex="-1"></a>  store_te[i] <span class="ot">&lt;-</span> lm_tmp<span class="sc">$</span>coefficients[<span class="st">&quot;z_tmp&quot;</span>]</span>
<span id="cb53-21"><a href="analysis.html#cb53-21" tabindex="-1"></a>}</span>
<span id="cb53-22"><a href="analysis.html#cb53-22" tabindex="-1"></a></span>
<span id="cb53-23"><a href="analysis.html#cb53-23" tabindex="-1"></a><span class="co"># Estimate treatment effect from actual assignment:</span></span>
<span id="cb53-24"><a href="analysis.html#cb53-24" tabindex="-1"></a>te_est <span class="ot">&lt;-</span> lm_out<span class="sc">$</span>coefficients[<span class="st">&quot;z&quot;</span>]</span>
<span id="cb53-25"><a href="analysis.html#cb53-25" tabindex="-1"></a></span>
<span id="cb53-26"><a href="analysis.html#cb53-26" tabindex="-1"></a><span class="co"># The p-value:</span></span>
<span id="cb53-27"><a href="analysis.html#cb53-27" tabindex="-1"></a><span class="co"># &quot;What proportion of effects estimated under sharp null hypothesis</span></span>
<span id="cb53-28"><a href="analysis.html#cb53-28" tabindex="-1"></a><span class="co">#  are at least as extreme as that which we observed?&quot;</span></span>
<span id="cb53-29"><a href="analysis.html#cb53-29" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">abs</span>(store_te) <span class="sc">&gt;=</span> <span class="fu">abs</span>(te_est))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Sometimes, this will differ greatly from the parametric <span class="math inline">\(p\)</span>-value. Here, the
parametric <span class="math inline">\(p\)</span>-value is 0.00482.</p>
<p>For another example, see <span class="citation">Gerber and Green (<a href="#ref-gergre12">2012</a>)</span>, Chapter 3 for a demonstration using highly skewed data.</p>
</div>
<div id="addressing-non-compliance" class="section level2 hasAnchor" number="4.8">
<h2><span class="header-section-number">4.8</span> Addressing Non-compliance<a href="analysis.html#addressing-non-compliance" class="anchor-section" aria-label="Anchor link to header"></a></h2>
</div>
<div id="missing-data" class="section level2 hasAnchor" number="4.9">
<h2><span class="header-section-number">4.9</span> Missing Data<a href="analysis.html#missing-data" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Unless we have solid justification to believe the missingness mechanism is MCAR
(missing completely at random), we prefer to treat missing data with multiple
imputation.</p>
<p>We recognize that not all missing data are the same, however. We can confidently
impute values that we are certain exist, but we should be more circumspect
regarding other values. For example, we can confidently impute a household
income, but we should be more circumspect about a student’s grade point average
(GPA) or a survey preference. How would we interpret that GPA if the student
actually dropped out of school? How can we be confident that the survey
respondent actually has a preference for alternative <span class="math inline">\(A\)</span> or <span class="math inline">\(B\)</span>, rather than
being indifferent or having never considered the question?</p>
<p>After multiple imputation, we analyze each of the completed data sets and
combine estimates and uncertainties from across the completed data sets into a
single estimate and uncertainty.</p>
</div>
<div id="multiple-comparisons" class="section level2 hasAnchor" number="4.10">
<h2><span class="header-section-number">4.10</span> Multiple Comparisons<a href="analysis.html#multiple-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In frequentist hypothesis testing, the more tests we conduct, the more likely we
become to “detect” a causal effect that isn’t real, but is only an artifact of
natural variation and random assignment. However, we are often interested in
learning as much as we can from an experiment, such as the effect of an
intervention on several outcomes, or the effect in subgroups, or the effect of
several conditions. This tension underlies the problem of multiple comparisons.</p>
<p>One way to avoid this problem is to use Bayesian multilevel modeling, where
post-analysis adjustment to probability statements or uncertainty intervals is
usually not necessarily <span class="citation">(<a href="#ref-gelhilyaj12">Gelman, Hill, and Yajima 2012</a>)</span>.</p>
<p>Another approach is to adjust frequentist <span class="math inline">\(p\)</span>-values. Our default strategy for
multiple comparisons is to control the family-wise error rate (FWER). This
approach also controls the false discovery rate (FDR), but can be very
conservative.</p>
<p>We account for multiple tests when a) we declare the tests to be confirmatory,
and b) the tests form a family. Otherwise, we do not account for multiple tests.</p>
<p>By default, we control the FWER using the Holm-Bonferroni procedure <span class="citation">(<a href="#ref-holm79">Holm 1979</a>)</span>.
With many tests or correlated tests, this adjustment can result in significant
losses in power. When we anticipate highly correlated tests, such as testing
several outcome measures of the same construct, or are interested in interval
estimation, we use a bootstrap resampling procedure <span class="citation">(<a href="#ref-wesyou93">Westfall and Young 1993</a>)</span>.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a></p>
<p>If we test a single outcome in several time periods, these tests are likely to
be highly correlated with each other. For example, in the ATE project, we expect
to test whether treatment affected the outcome at 3 months and at 6 months. In
such cases, we adjust for performing two tests using the bootstrap resampling
procedure of <span class="citation">Westfall and Young (<a href="#ref-wesyou93">1993</a>)</span>.</p>
<div id="holm-bonferroni-adjustment" class="section level3 hasAnchor" number="4.10.1">
<h3><span class="header-section-number">4.10.1</span> Holm-Bonferroni Adjustment<a href="analysis.html#holm-bonferroni-adjustment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we have conducted three confirmatory hypothesis tests in a family, with
<span class="math inline">\(p\)</span>-values <span class="math inline">\(p_1 = .01\)</span>, <span class="math inline">\(p_2 = .02\)</span>, and <span class="math inline">\(p_3 = .08\)</span>, in increasing order. To
adjust these <span class="math inline">\(p\)</span>-values with the Holm procedure, we use</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="analysis.html#cb55-1" tabindex="-1"></a><span class="fu">p.adjust</span>(<span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.02</span>, <span class="fl">0.08</span>), <span class="at">method =</span> <span class="st">&quot;holm&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 0.03 0.04 0.08</code></pre>
<p>We see that the three adjusted <span class="math inline">\(p\)</span>-values are <span class="math inline">\(0.03\)</span>, <span class="math inline">\(0.04\)</span>, and <span class="math inline">\(0.08\)</span>. (Here, these are <span class="math inline">\(p_1 \times 3\)</span>, <span class="math inline">\(p_2 \times 2\)</span>, and <span class="math inline">\(p_3 \times 1\)</span>.)</p>
</div>
<div id="westfall-young-adjustment" class="section level3 hasAnchor" number="4.10.2">
<h3><span class="header-section-number">4.10.2</span> Westfall-Young Adjustment<a href="analysis.html#westfall-young-adjustment" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><span class="citation">Westfall and Young (<a href="#ref-wesyou93">1993</a>)</span> provides a bootstrapping approach to <span class="math inline">\(p\)</span>-value adjustment that tends to be more powerful than the Holm-Bonferroni procedure.<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a> It strongly controls the FWER under the assumption of subset pivotality. We show an example using the implementation of <span class="citation">Hidalgo (<a href="#ref-hidalgo17">2017</a>)</span> below.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="analysis.html#cb57-1" tabindex="-1"></a><span class="co"># Add another outcome and centered covariate:</span></span>
<span id="cb57-2"><a href="analysis.html#cb57-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">y2 =</span> <span class="fl">0.5</span> <span class="sc">*</span> z <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(df), <span class="at">sd =</span> <span class="dv">1</span>),</span>
<span id="cb57-3"><a href="analysis.html#cb57-3" tabindex="-1"></a>                   <span class="at">x_c =</span> <span class="fu">as.vector</span>(<span class="fu">scale</span>(x, <span class="at">scale =</span> <span class="cn">FALSE</span>)))</span>
<span id="cb57-4"><a href="analysis.html#cb57-4" tabindex="-1"></a></span>
<span id="cb57-5"><a href="analysis.html#cb57-5" tabindex="-1"></a><span class="co"># Install multitestr:</span></span>
<span id="cb57-6"><a href="analysis.html#cb57-6" tabindex="-1"></a><span class="co"># devtools::install_github(&quot;fdhidalgo/multitestr&quot;)</span></span>
<span id="cb57-7"><a href="analysis.html#cb57-7" tabindex="-1"></a><span class="fu">library</span>(multitestr)</span>
<span id="cb57-8"><a href="analysis.html#cb57-8" tabindex="-1"></a></span>
<span id="cb57-9"><a href="analysis.html#cb57-9" tabindex="-1"></a><span class="co"># Define formulas with treatment (and interaction):</span></span>
<span id="cb57-10"><a href="analysis.html#cb57-10" tabindex="-1"></a>ff <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">list</span>(</span>
<span id="cb57-11"><a href="analysis.html#cb57-11" tabindex="-1"></a>  <span class="st">&quot;y ~ z + x_c + z * x_c&quot;</span>, </span>
<span id="cb57-12"><a href="analysis.html#cb57-12" tabindex="-1"></a>  <span class="st">&quot;y2 ~ z + x_c + z * x_c&quot;</span>),</span>
<span id="cb57-13"><a href="analysis.html#cb57-13" tabindex="-1"></a>  as.formula)</span>
<span id="cb57-14"><a href="analysis.html#cb57-14" tabindex="-1"></a></span>
<span id="cb57-15"><a href="analysis.html#cb57-15" tabindex="-1"></a><span class="co"># Define null formulas without treatment:</span></span>
<span id="cb57-16"><a href="analysis.html#cb57-16" tabindex="-1"></a>ff_null <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="fu">list</span>(</span>
<span id="cb57-17"><a href="analysis.html#cb57-17" tabindex="-1"></a>  <span class="st">&quot;y ~ x_c&quot;</span>, </span>
<span id="cb57-18"><a href="analysis.html#cb57-18" tabindex="-1"></a>  <span class="st">&quot;y2 ~ x_c&quot;</span>),</span>
<span id="cb57-19"><a href="analysis.html#cb57-19" tabindex="-1"></a>  as.formula)</span>
<span id="cb57-20"><a href="analysis.html#cb57-20" tabindex="-1"></a></span>
<span id="cb57-21"><a href="analysis.html#cb57-21" tabindex="-1"></a>wy_out <span class="ot">&lt;-</span> <span class="fu">boot_stepdown</span>(</span>
<span id="cb57-22"><a href="analysis.html#cb57-22" tabindex="-1"></a>  <span class="at">full_formulas =</span> ff,</span>
<span id="cb57-23"><a href="analysis.html#cb57-23" tabindex="-1"></a>  <span class="at">null_formulas =</span> ff_null,</span>
<span id="cb57-24"><a href="analysis.html#cb57-24" tabindex="-1"></a>  <span class="at">data =</span> df,</span>
<span id="cb57-25"><a href="analysis.html#cb57-25" tabindex="-1"></a>  <span class="at">coef_list =</span> <span class="fu">list</span>(<span class="at">coef =</span> <span class="fu">c</span>(<span class="st">&quot;z&quot;</span>, <span class="st">&quot;z:x_c&quot;</span>)),</span>
<span id="cb57-26"><a href="analysis.html#cb57-26" tabindex="-1"></a>  <span class="at">nboots =</span> <span class="dv">1000</span>,</span>
<span id="cb57-27"><a href="analysis.html#cb57-27" tabindex="-1"></a>  <span class="at">parallel =</span> <span class="cn">FALSE</span>,</span>
<span id="cb57-28"><a href="analysis.html#cb57-28" tabindex="-1"></a>  <span class="at">boot_type =</span> <span class="st">&quot;wild&quot;</span>,</span>
<span id="cb57-29"><a href="analysis.html#cb57-29" tabindex="-1"></a>  <span class="at">pb =</span> <span class="cn">FALSE</span>)</span>
<span id="cb57-30"><a href="analysis.html#cb57-30" tabindex="-1"></a></span>
<span id="cb57-31"><a href="analysis.html#cb57-31" tabindex="-1"></a>wy_out <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), </span>
<span id="cb57-32"><a href="analysis.html#cb57-32" tabindex="-1"></a>                        \(x) <span class="fu">round</span>(x, <span class="dv">3</span>)))</span></code></pre></div>
<pre><code>##     Hypothesis  coef bs_pvalues_unadjusted bs_pvalues_adjusted
## 1 Hypothesis 1     z                 0.001               0.001
## 2 Hypothesis 2 z:x_c                 0.148               0.268
## 3 Hypothesis 1     z                 0.073               0.247
## 4 Hypothesis 2 z:x_c                 0.180               0.268</code></pre>
</div>
</div>
<div id="posterior-probabilities" class="section level2 hasAnchor" number="4.11">
<h2><span class="header-section-number">4.11</span> Posterior Probabilities<a href="analysis.html#posterior-probabilities" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We may be interested in the probability that one treatment condition outperforms
another. In <span class="citation">Moore et al. (<a href="#ref-mooganmin22">2022</a>)</span>, we calculate that open deadlines have probability 0.79
of being better than specific deadlines. These probabilities can provide
guidance for agencies about which treatment condition(s) to continue
implementing after an experiment ends, especially when there appears to be
little difference between conditions in effect or cost.</p>

</div>
</div>
<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-avimammoo23" class="csl-entry">
Avila, Maria, Natnaell Mammo, Ryan T. Moore, and Sam Quinney. 2023. <span>“Do Shallow Rental Subsidies Promote Housing Stability? Evidence on Costs and Effects from DC’s Shallow Flexible Rent Subsidy Program.”</span> <em>Urban Affairs Review</em> 59 (5): 1530–66. <a href="https://doi.org/10.1177/10780874221111140">https://doi.org/10.1177/10780874221111140</a>.
</div>
<div id="ref-blacoocop22" class="csl-entry">
Blair, Graeme, Jasper Cooper, Alexander Coppock, Macartan Humphreys, and Luke Sonnet. 2022. <em>Estimatr: Fast Estimators for Design-Based Inference</em>. <a href="https://CRAN.R-project.org/package=estimatr">https://CRAN.R-project.org/package=estimatr</a>.
</div>
<div id="ref-gelhilyaj12" class="csl-entry">
Gelman, Andrew, Jennifer Hill, and Masanao Yajima. 2012. <span>“Why We (Usually) Don’t Have to Worry about Multiple Comparisons.”</span> <em>Journal of Research on Educational Effectiveness</em> 5 (2): 189–211. <a href="https://doi.org/10.1080/19345747.2011.618213">https://doi.org/10.1080/19345747.2011.618213</a>.
</div>
<div id="ref-gergre12" class="csl-entry">
Gerber, Alan S., and Donald P. Green. 2012. <em>Field Experiments: Design, Analysis, and Interpretation</em>. WW Norton.
</div>
<div id="ref-hidalgo17" class="csl-entry">
Hidalgo, F. Daniel. 2017. <em>Multitestr: Resampling-Based Multiple Testing Adjustments for Linear Regression</em>.
</div>
<div id="ref-holm79" class="csl-entry">
Holm, Sture. 1979. <span>“A Simple Sequentially Rejective Multiple Test Procedure.”</span> <em>Scandinavian Journal of Statistics</em> 6: 65–70.
</div>
<div id="ref-lin2013" class="csl-entry">
Lin, Winston. 2013. <span>“Agnostic Notes on Regression Adjustments to Experimental Data: Reexamining Freedman’s Critique.”</span> <em>The Annals of Applied Statistics</em> 7 (1): 295–318.
</div>
<div id="ref-mooganmin22" class="csl-entry">
Moore, Ryan T., Katherine N. Gan, Karissa Minnich, and David Yokum. 2022. <span>“Anchor Management: A Field Experiment to Encourage Families to Meet Critical Programme Deadlines.”</span> <em>Journal of Public Policy</em> 42 (4): 615–36. <a href="https://doi.org/10.1017/S0143814X21000131">https://doi.org/10.1017/S0143814X21000131</a>.
</div>
<div id="ref-morgan17" class="csl-entry">
Morgan, Kari Lock. 2017. <span>“Reallocating and Resampling: A Comparison for Inference.”</span> arXiv. <a href="https://doi.org/10.48550/ARXIV.1708.02102">https://doi.org/10.48550/ARXIV.1708.02102</a>.
</div>
<div id="ref-rugfol21" class="csl-entry">
Ruggeri, Kai, and Tomas Folke. 2021. <span>“Unstandard Deviation: The Untapped Value of Positive Deviance for Reducing Inequalities.”</span> <em>Perspectives on Psychological Science</em>. <a href="https://doi.org/10.1177/17456916211017865">https://doi.org/10.1177/17456916211017865</a>.
</div>
<div id="ref-tukey91" class="csl-entry">
Tukey, John W. 1991. <span>“Use of Many Covariates in Clinical Trials.”</span> <em>International Statistical Review</em> 59 (2): 123–37.
</div>
<div id="ref-wesyou93" class="csl-entry">
Westfall, Peter H., and S. Stanley Young. 1993. <em>Resampling-Based Multiple Testing: Examples and Methods for p-Value Adjustment</em>. John Wiley &amp; Sons.
</div>
</div>
<div class="footnotes">
<hr />
<ol start="2">
<li id="fn2"><p><span class="citation">Gerber and Green (<a href="#ref-gergre12">2012</a>)</span> provides an instructive example.<a href="analysis.html#fnref2" class="footnote-back">↩︎</a></p></li>
<li id="fn3"><p>In the
original paper, <span class="citation">Lin (<a href="#ref-lin2013">2013</a>)</span> describes “the OLS regression of <span class="math inline">\(Y_i\)</span> on <span class="math inline">\(T_i\)</span>, <span class="math inline">\(z_i\)</span>,
and <span class="math inline">\(T_i(z_i − \bar{z})\)</span>”, where the covariates are only centered in the
interaction. The implementation in <span class="citation">Blair et al. (<a href="#ref-blacoocop22">2022</a>)</span> and Lin’s supplementary materials, however, center the covariates
in their linear terms, using <span class="math inline">\(T_i\)</span>, <span class="math inline">\(z_i-\bar{z}\)</span>, and <span class="math inline">\(T_i(z_i − \bar{z})\)</span>. We
show elsewhere that it doesn’t matter which of these models we estimate.<a href="analysis.html#fnref3" class="footnote-back">↩︎</a></p></li>
<li id="fn4"><p>The
intuition: if the treatment and control groups look different, then we up-weight
the controls that look more like the treateds, and vice versa. If you’re a
control that looks like all the other controls, you’re less informative about
the causal effect than if you’re a control that looks like the treateds.<a href="analysis.html#fnref4" class="footnote-back">↩︎</a></p></li>
<li id="fn5"><p>This procedure
strongly controls the FWER under <em>subset pivotality</em>, a condition likely to
obtain when we estimate the effect of a single treatment on many outcomes.<a href="analysis.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p><span class="citation">Morgan (<a href="#ref-morgan17">2017</a>)</span> shows that resampling and reallocation methods behave very similarly (up to <span class="math inline">\(\frac{n-1}{n}\)</span>) in testing, and argues that, for interval estimation, we should prefer bootstrap resampling methods to reallocation methods (which depend on an equal-variances assumption and additivity).<a href="analysis.html#fnref6" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="implementation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="observational-studies.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
